# Generated by Django 4.1 on 2022-11-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catagaries_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('Individual_name', models.CharField(max_length=200)),
                ('Individual_address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='research_Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('skills', models.CharField(default='None', max_length=500)),
                ('is_active', models.BooleanField(default=False)),
                ('typeof', models.CharField(choices=[('Freelancer', 'Freelancer'), ('Employee', 'Employee'), ('Internship', 'Internship'), ('Research Associate', 'Research Associate')], default='Freelance', max_length=100)),
                ('city', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(max_length=132, null=True)),
                ('others', models.JSONField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
