# Generated by Django 4.0.6 on 2022-08-31 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=100)),
                ('Age', models.CharField(max_length=100)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('other', 'other')], max_length=50)),
                ('qualification', models.CharField(choices=[("Master's Degree", "Master's Degree"), ("Bachelor's Degree", "Bachelor's Degree"), ('Higher Secondary School', 'Higher Secondary School'), ('Secondary School', 'Secondary School'), ('No Formal Schooling', 'No Formal Schooling'), ('Other', 'Other')], max_length=100)),
                ('income', models.CharField(choices=[('Low income', 'Low income'), ('Middle income', 'Middle income'), ('High income', 'High income')], max_length=50)),
                ('Occupation', models.CharField(max_length=100)),
                ('comments', models.CharField(max_length=100)),
                ('Name_suggestion', models.CharField(max_length=100)),
                ('Other', models.JSONField()),
            ],
        ),
    ]
