# Generated by Django 4.1.1 on 2022-10-08 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.CharField(max_length=100)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('other', 'other')], max_length=50)),
                ('qualification', models.CharField(choices=[("Master's Degree", "Master's Degree"), ("Bachelor's Degree", "Bachelor's Degree"), ('Higher Secondary School', 'Higher Secondary School'), ('Secondary School', 'Secondary School'), ('No Formal Schooling', 'No Formal Schooling'), ('Other', 'Other')], max_length=100)),
                ('income', models.CharField(choices=[('Low income', 'Low income'), ('Middle income', 'Middle income'), ('High income', 'High income')], max_length=50)),
                ('Occupation', models.CharField(max_length=100)),
                ('comments', models.CharField(max_length=100)),
                ('Name_suggestion', models.CharField(max_length=100)),
                ('status', models.CharField(default='Pending', max_length=132, null=True)),
                ('Other', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('skills', models.CharField(default='None', max_length=500)),
                ('is_active', models.BooleanField(default=False)),
                ('typeof', models.CharField(choices=[('Freelancer', 'Freelancer'), ('Employee', 'Employee'), ('Internship', 'Internship'), ('Research Associate', 'Research Associate')], default='Freelance', max_length=100)),
                ('location', models.CharField(max_length=132, null=True)),
                ('others', models.JSONField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.country')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.CharField(max_length=100)),
                ('status', models.CharField(default='Pending', max_length=132, null=True)),
                ('Age', models.CharField(max_length=100, null=True)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('other', 'other')], max_length=50, null=True)),
                ('qualification', models.CharField(choices=[("Master's Degree", "Master's Degree"), ("Bachelor's Degree", "Bachelor's Degree"), ('Higher Secondary School', 'Higher Secondary School'), ('Secondary School', 'Secondary School'), ('No Formal Schooling', 'No Formal Schooling'), ('Other', 'Other')], max_length=100, null=True)),
                ('income', models.CharField(choices=[('Low income', 'Low income'), ('Middle income', 'Middle income'), ('High income', 'High income')], max_length=50, null=True)),
                ('Occupation', models.CharField(max_length=100, null=True)),
                ('others', models.JSONField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.job')),
            ],
            options={
                'verbose_name_plural': 'Job Applications',
            },
        ),
    ]
