# Generated by Django 4.1.1 on 2022-09-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitytable',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Done')], null=True),
        ),
    ]
