# Generated by Django 4.1.1 on 2022-09-20 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_communitytable_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.CharField(max_length=100)),
                ('feedBack', models.TextField(null=True)),
                ('country', models.CharField(max_length=132, null=True)),
                ('hr_remarks', models.CharField(max_length=500, null=True)),
                ('status', models.CharField(default='Pending', max_length=132, null=True)),
                ('others', models.JSONField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.communitytable')),
            ],
            options={
                'verbose_name_plural': 'Job Applications',
            },
        ),
    ]
