# Generated by Django 4.1.1 on 2022-09-20 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_jobapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.CharField(max_length=100)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('other', 'other')], max_length=50)),
                ('qualification', models.CharField(choices=[("Master's Degree", "Master's Degree"), ("Bachelor's Degree", "Bachelor's Degree"), ('Higher Secondary School', 'Higher Secondary School'), ('Secondary School', 'Secondary School'), ('No Formal Schooling', 'No Formal Schooling'), ('Other', 'Other')], max_length=100)),
                ('income', models.CharField(choices=[('Low income', 'Low income'), ('Middle income', 'Middle income'), ('High income', 'High income')], max_length=50)),
                ('Occupation', models.CharField(max_length=100)),
                ('comments', models.CharField(max_length=100)),
                ('Name_suggestion', models.CharField(max_length=100)),
                ('status', models.SmallIntegerField(default='Pending', max_length=132, null=True)),
                ('Other', models.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.job'),
        ),
        migrations.DeleteModel(
            name='CommunityTable',
        ),
    ]
