# Generated by Django 4.1.1 on 2022-10-10 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_jobapplication_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='country',
        ),
    ]
