# Generated by Django 4.1.1 on 2022-09-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_job_alter_jobapplication_job_delete_communitytable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(default='Pending', max_length=132, null=True),
        ),
    ]
